spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: dm-user
          uri: lb://dm-user
          predicates:
            - Path=/dm-user/**
          filters:
            - StripPrefix=1
            - RequestPath=test,path