spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: dm-security
          uri: lb://dm-security
          predicates:
            - Path=/dm-security/**
          filters:
            - StripPrefix=1
        - id: dm-user
          uri: lb://dm-user
          predicates:
            - Path=/dm-user/**
          filters:
            - StripPrefix=1
            - RequestPath=test,path
        - id: websocket
          uri: lb:ws://dm-framework-websocket
          predicates:
            - Path=/websocket/**
        - id: dm-chat
          #uri: ws://127.0.0.1:12345
          uri: lb:ws://dm-chat
          predicates:
            - Path=/dm-chat/ws/**
          filters:
            - StripPrefix=1
      # 跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"  #允许所有ip跨域访问
            allowedMethods: "*"  #允许所有请求方式
            allowedHeaders: "*"  #允许任何头进行跨域
            allowCredentials: true #允许携带cookie
            ## 以上配完成，简单跨域复杂跨域都允许。