server:
  port: 8081
spring:
  application:
    name: dm-gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: dm-user
          uri: lb://dm-user
          predicates:
            - Path=/dm-user/**
          #filters:
          #  - StripPrefix=1
