spring:
  # 自定义redisson配置
  redisson:
    # 自定义的key，RedissonConfig中配置使用
    type: single
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: dm-user
          uri: lb://dm-user
          predicates:
            - Path=/dm-user/**
          filters:
            - StripPrefix=1
            - RequestPath=test,path